import pytest

from github_repo_chat.core.file_filter import decode_text, is_candidate, language_for, priority

MAX = 200_000


@pytest.mark.parametrize(
    ("path", "language"),
    [
        ("README", "text"),
        ("readme.rst", "rst"),
        ("docs/guide.md", "markdown"),
        ("docs/page.mdx", "markdown"),
        ("notes.txt", "text"),
        ("src/app.py", "python"),
        ("web/App.TSX", "tsx"),
        ("web/app.jsx", "javascript"),
        ("lib/x.h", "c"),
        ("Main.cs", "csharp"),
        ("image.png", None),
        ("data.json", None),
        ("Makefile", None),
    ],
)
def test_language_for_maps_extensions(path: str, language: str | None) -> None:
    assert language_for(path) == language


@pytest.mark.parametrize(
    "path",
    ["README.md", "src/pkg/core.py", "docs/index.rst", "cmd/main.go", "src/lib.rs", "a/b/c.ts"],
)
def test_is_candidate_accepts_docs_and_source(path: str) -> None:
    assert is_candidate(path, 1000, MAX)


@pytest.mark.parametrize(
    "path",
    [
        "tests/test_core.py",
        "src/tests/helpers.py",
        "pkg/spec/thing.rb",
        "src/__tests__/a.js",
        "node_modules/x/index.js",
        "vendor/lib/a.go",
        "dist/bundle.js",
        "build/out.py",
        ".github/README.md",
        "src/.hidden/a.py",
        "test_core.py",
        "core_test.go",
        "app.test.ts",
        "app.spec.jsx",
        "FooTest.java",
        "jquery.min.js",
        "yarn.lock",
        "api_pb2.py",
        "api.pb.go",
        "client.generated.ts",
        "types.d.ts",
        "logo.png",
    ],
)
def test_is_candidate_rejects_excluded_paths(path: str) -> None:
    assert not is_candidate(path, 1000, MAX)


def test_is_candidate_rejects_large_files() -> None:
    assert is_candidate("a.py", MAX, MAX)
    assert not is_candidate("a.py", MAX + 1, MAX)


def test_decode_text_returns_utf8_text() -> None:
    assert decode_text("a.py", "print('è')\n".encode()) == "print('è')\n"


def test_decode_text_rejects_binary_and_invalid_utf8() -> None:
    assert decode_text("a.py", b"abc\x00def") is None
    assert decode_text("a.md", b"\xff\xfe\xfa") is None


def test_decode_text_rejects_minified_code_but_keeps_long_doc_lines() -> None:
    long_line = "x" * 1001
    assert decode_text("a.js", long_line.encode()) is None
    assert decode_text("a.md", long_line.encode()) == long_line


def test_decode_text_rejects_generated_code() -> None:
    header = b"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n"
    assert decode_text("x.go", header) is None
    assert decode_text("x.md", header) is not None


def test_priority_orders_readme_docs_then_source_by_depth() -> None:
    paths = ["src/deep/a.py", "b.py", "docs/guide.md", "CHANGES.md", "docs/README.md", "README.md"]
    assert sorted(paths, key=priority) == [
        "README.md",
        "docs/README.md",
        "CHANGES.md",
        "docs/guide.md",
        "b.py",
        "src/deep/a.py",
    ]
